package org.vinni.cliente.gui;


import javax.swing.*;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;


/**
 * author: Vinni 2024
 *
 */
public class PrincipalCliMod extends javax.swing.JFrame {


    private final int PORT = 12345;
    private Socket socket;
    private PrintWriter out;
    private BufferedReader in;


    /**
     * Creates new form Principal1
     */
    public PrincipalCliMod() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {


        this.setTitle("Cliente ");
        bConectar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensajesTxt = new javax.swing.JTextArea();
        mensajeTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btEnviar = new javax.swing.JButton();
        jLabelIp = new javax.swing.JLabel();
        ipTxt = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);


        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("CLIENTE TCP : DFRACK");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 10, 250, 17);


        jLabelIp.setFont(new java.awt.Font("Verdana", 0, 12));
        jLabelIp.setText("IP Servidor:");
        getContentPane().add(jLabelIp);
        jLabelIp.setBounds(20, 40, 90, 20);


        ipTxt.setFont(new java.awt.Font("Verdana", 0, 12));
        ipTxt.setText("localhost");
        getContentPane().add(ipTxt);
        ipTxt.setBounds(115, 38, 130, 25);


        jLabelNombre.setFont(new java.awt.Font("Verdana", 0, 12));
        jLabelNombre.setText("Usuario:");
        getContentPane().add(jLabelNombre);
        jLabelNombre.setBounds(255, 40, 70, 20);


        nombreTxt.setFont(new java.awt.Font("Verdana", 0, 12));
        getContentPane().add(nombreTxt);
        nombreTxt.setBounds(325, 38, 130, 25);


        bConectar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bConectar.setText("CONECTAR CON SERVIDOR");
        bConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConectarActionPerformed(evt);
            }
        });
        getContentPane().add(bConectar);
        bConectar.setBounds(130, 75, 230, 35);


        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Mensaje:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 125, 120, 30);


        mensajeTxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(mensajeTxt);
        mensajeTxt.setBounds(40, 155, 350, 30);


        btEnviar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btEnviar.setText("Enviar");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btEnviar);
        btEnviar.setBounds(327, 195, 120, 27);


        mensajesTxt.setColumns(20);
        mensajesTxt.setRows(5);
        mensajesTxt.setEnabled(false);
        jScrollPane1.setViewportView(mensajesTxt);


        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 240, 410, 110);


        setSize(new java.awt.Dimension(491, 410));
        setLocationRelativeTo(null);
    }// </editor-fold>


    private void bConectarActionPerformed(java.awt.event.ActionEvent evt) {
        conectar();
    }


    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {
        this.enviarMensaje();
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalCliMod().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify
    private javax.swing.JButton bConectar;
    private javax.swing.JButton btEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mensajesTxt;
    private JTextField mensajeTxt;
    private javax.swing.JLabel jLabelIp;
    private javax.swing.JTextField ipTxt;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JTextField nombreTxt;
    // End of variables declaration


    private void conectar() {
        String ipServidor = ipTxt.getText().trim();
        if (ipServidor.isEmpty()) {
            ipServidor = "localhost";
        }
        JOptionPane.showMessageDialog(this, "Conectando con servidor " + ipServidor + ":" + PORT);
        try {
            if (socket == null || socket.isClosed()) {
                // La IP ya no está fija: se toma del campo de texto, para
                // poder apuntar a la máquina donde se ejecuta el servidor
                // (localhost para pruebas locales, o la IP de red para
                // conectarse desde otro computador).
                socket = new Socket(ipServidor, PORT);
                out = new PrintWriter(socket.getOutputStream(), true);
                in = new BufferedReader(new InputStreamReader(socket.getInputStream()));


                // Deshabilita el botón para evitar reconexiones accidentales
                // que crearían varios hilos lectores sobre el mismo socket.
                bConectar.setEnabled(false);


                new Thread(new Runnable() {
                    public void run() {
                        try {
                            String fromServer;
                            while ((fromServer = in.readLine()) != null) {
                                final String linea = fromServer;
                                // Los componentes Swing solo deben tocarse desde
                                // el hilo de eventos (EDT).
                                SwingUtilities.invokeLater(() -> mensajesTxt.append(linea + "\n"));
                            }
                        } catch (IOException ex) {
                            SwingUtilities.invokeLater(() ->
                                mensajesTxt.append("Se perdió la conexión con el servidor.\n"));
                        } finally {
                            SwingUtilities.invokeLater(() -> bConectar.setEnabled(true));
                        }
                    }
                }).start();
                System.out.println(out);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "No se pudo conectar al servidor " + ipServidor + ": " + e.getMessage());
        }
    }


    private void enviarMensaje() {
        if (out == null) {
            JOptionPane.showMessageDialog(this, "Primero debe conectarse al servidor.");
            return;
        }
        String nombre = nombreTxt.getText().trim();
        String texto = mensajeTxt.getText();
        String mensaje = nombre.isEmpty() ? texto : (nombre + ": " + texto);
        out.println(mensaje);
        mensajeTxt.setText("");
    }
}
